### ISSUE TITLE
Site Page Template for the Sub Communities of ODevs

### ISSUE THREAD

**Issue by paulo-desouza** [snohio/odevs#7]
# Sub Community Page Template

## User Story

As a member of Orlando DevOps group, I would like to create an 11ty template so that the sub communities have a standard and easy way of creating their ODev pages. 

## Tasks

- [x] Add a drop down menu on the "About Us"  to include all the current communities that have their sub-pages created
- [x] Create an 11ty page to contain all of a sub community's information, links and logo

**Comment by wgeorgecook** [comment]
Fixed by https://github.com/snohio/odevs/pull/20
